Implement insert tx

diff --git a/insert_or_update b/insert_or_update
--- a/insert_or_update
+++ b/insert_or_update
@@ -3,6 +3,13 @@
 main() {
 	DIR=$(dirname $0)
 
+	source $DIR/config
+
+	if [ "$DB" = "" ]; then
+		printf "Error: DB not configured"
+		exit 1
+	fi
+
 	printf "am? "
 	read amount
 
@@ -20,15 +27,17 @@ main() {
 
 	date=$(sh $DIR/parse_date "$date")
 
-	format="insert into t (d, a, f, t, c) values"
-	format="$format ('%s', %d, '%s', '%s', '%s');"
+	sqlite3 "$DB" <<EOD
+insert into t (d, a, f, t, c) values (
+	'$date',
+	$amount,
+	'$(echo $from | escape_quotes)',
+	'$(echo $to | escape_quotes)',
+	'$(echo $comment | escape_quotes)'
+);
 
-	printf "$format" \
-		$date \
-		$amount \
-		"$(echo $from | escape_quotes)" \
-		"$(echo $to | escape_quotes)" \
-		"$(echo $comment | escape_quotes)"
+select last_insert_rowid();
+EOD
 }
 
 escape_quotes() {
